name: Cypress Tests

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Start application
        run: npm start &

      - name: Wait for server
        run: npx wait-on http://127.0.0.1:5500 --timeout 60000

      - name: Run Cypress
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          headless: true
          args: --disable-gpu

      - name: Upload Cypress artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-results
          path: |
            cypress/videos
            cypress/screenshots
