name: Cypress Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        
      # Se sua app precisa rodar para o Cypress testar
      - name: Start application
        run: npm start &
        
      - name: Wait for app to be ready
        run: npx wait-on http://localhost:3000
        
      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          headless: true

      # Upload artifacts (vídeos, screenshots)
      - name: Upload Cypress Artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-results
          path: |
            cypress/videos
            cypress/screenshots
